# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/config.html

[build]


[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
#rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.x86_64-pc-windows-gnu]
#rustflags = ["-C", "link-args=-Wl,--subsystem,windows -mwindows"]
[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "link-args=/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]